version: "3.7"
services:
  typescript:
    build:
      context: .
    init: true
    volumes:
      - $HOME/.aws:/root/.aws
      - history-vol:/history
      - app-vol:/app

volumes:
  history-vol:
  app-vol:
